// AUTO-GENERATED by scripts/gen-api-types.mjs from openapi/schema.json — do NOT edit manually.
// Re-run `npm run api:types` after refreshing openapi/schema.json (`npm run api:schema`).

export interface paths {
    "/api/atmosphere/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Atmosphere
         * @description Suggest the best atmosphere model for a given launch date.
         *
         *     Calls ``choose_atmosphere_model_for_date`` from the icaro domain — the
         *     router encodes NO decision logic itself (RG-1.1, RG-1.5).
         *
         *     Returns
         *     -------
         *     dict
         *         ``{model, reason, within_gfs_window, needs_internet}``
         *
         *     Satisfies AC-RG-2.7, AC-RG-2.8, RG-2.6.
         */
        get: operations["suggest_atmosphere_api_atmosphere_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie. Always succeeds, even on a stale cookie.
         *
         *     Best-effort revokes the underlying refresh token so a captured cookie
         *     value cannot keep verifying after logout.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the caller's identity — lets the browser confirm it's signed in.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Verify the Identity Platform ID token and set the session cookie.
         *
         *     401 on an invalid/expired ID token, 403 when the account has no
         *     ``org_id`` claim yet — never a 500 (RG-9.4 pattern).
         */
        post: operations["create_session_api_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Convert
         * @description Convert a .ork file to an export directory and persist artifacts.
         *
         *     Multipart upload → ``convert_ork`` → upload export dir to Storage
         *     under ``orgs/{org_id}/exports/{run_id}/`` → save RocketRecord to Db →
         *     returns ``{export_id, manifest}`` where ``export_id`` is a logical
         *     run_id slug.
         *
         *     On ``ConvertUnavailableError``: 503 with the install hint verbatim.
         *     On non-.ork file: 422.
         *     Never returns a Python traceback (RG-9.4).
         *
         *     Satisfies RG-2.1, AC-RG-2.1, AC-RG-2.2, REQ-01.1, REQ-02.1, REQ-03.1.
         */
        post: operations["post_convert_api_convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/elevation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Elevation
         * @description Look up ground elevation at the given coordinates.
         *
         *     Best-effort: on failure returns 503 (AC-RG-2.9).  The UI must handle
         *     this gracefully (show manual-entry fallback, never block simulate).
         *
         *     Satisfies RG-2.7, AC-RG-2.9.
         */
        get: operations["get_elevation_api_elevation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History
         * @description Return a paginated list of simulations in reverse-chronological order.
         *
         *     Each item includes a denormalized rocket ``name`` fetched via
         *     ``db.get_rocket`` (join-on-read — see module docstring for rationale).
         *
         *     Parameters
         *     ----------
         *     limit : int
         *         Maximum number of records (default: 20, max: 100).
         *     before : datetime | None
         *         Cursor — return only simulations created before this timestamp.
         *
         *     Satisfies REQ-05.1, REQ-05.2, REQ-05.3.
         */
        get: operations["list_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result
         * @description Return the result for a completed run in forward-compat job-status shape.
         *
         *     Response shape: ``{run_id, status: "done", result}``
         *
         *     The shape is designed for forward-compat with an async/polling upgrade
         *     (ADR-6): when simulate becomes async, this endpoint will return
         *     ``{run_id, status: "running"|"done"|"error", progress?, result?}`` and
         *     the client polls — no contract break.
         *
         *     Fetches ``{result_prefix}result.json`` via the Storage seam (REQ-02.4),
         *     where ``result_prefix`` comes from the resolved SimRecord (issue #45).
         *     Returns 404 if the run is absent or not owned by the caller's org.
         */
        get: operations["get_result_api_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}/plots/{name}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plot
         * @description Serve a plot PNG from Storage.
         *
         *     Fetches ``{result_prefix}{name}.png`` via the Storage seam (REQ-02.5),
         *     where ``result_prefix`` comes from the resolved SimRecord (issue #45).
         *     Returns 404 if the run is absent or not owned by the caller's org, or the
         *     plot blob itself is missing. PNGs are the artifacts most likely to be
         *     linked or embedded directly, so this check applies here too, not just to
         *     the JSON endpoints (issue #44).
         *
         *     The ``name`` segment is sanitised (``Path.name``) to prevent directory
         *     traversal — same guard as the previous local-disk implementation.
         */
        get: operations["get_plot_api_results__run_id__plots__name__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description Return the resampled flight time-series for a completed run (issue #11).
         *
         *     Shape: ``{t, altitude, speed, mach, acceleration, path3d}`` — plain JSON
         *     arrays sharing one ``t`` axis, written by ``serialize_flight`` at simulate
         *     time. Powers the interactive 2D charts and the animated 3D trajectory.
         *
         *     Fetches ``{result_prefix}series.json`` via the Storage seam (REQ-02.6),
         *     where ``result_prefix`` comes from the resolved SimRecord (issue #45).
         *     Returns 404 if the run is absent, not owned by the caller's org, or the
         *     blob itself is missing (e.g. an old run predating this feature) — the
         *     client then falls back to the static PNG plots. Additive endpoint.
         */
        get: operations["get_series_api_results__run_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rockets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rockets
         * @description Return a paginated list of saved rockets in reverse-chronological order.
         *
         *     Parameters
         *     ----------
         *     limit : int
         *         Maximum number of records (default: 20, max: 100).
         *     before : datetime | None
         *         Cursor — return only rockets created before this timestamp (ISO 8601).
         *
         *     Satisfies REQ-04.1, REQ-04.2, REQ-04.3.
         */
        get: operations["list_rockets_api_rockets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rockets/{rocket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rocket
         * @description Return the full rocket record including manifest and gcs_ref.
         *
         *     The ``manifest`` is the single source of truth in object storage
         *     (``parameters.json`` under the export prefix), NOT Firestore — it can
         *     contain nested arrays that Firestore Native rejects (see
         *     ``FirestoreDb.save_rocket``). It is loaded here from Storage and degrades to
         *     ``{}`` if the blob is missing, so the endpoint never 500s on a stale record.
         *
         *     Returns 404 if the rocket_id is not found OR not owned by the caller's org.
         *     Satisfies REQ-04.4.
         */
        get: operations["get_rocket_api_rockets__rocket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario Template
         * @description Return a starter Scenario dict with DEFAULT_UNCERTAINTY and PRESETS.
         *
         *     The UI uses this as its initial form state — it never starts empty.
         *     Satisfies AC-RG-2.3, RG-2.2.
         */
        get: operations["get_scenario_template_api_scenario_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Scenario
         * @description Validate and normalize a scenario dict.
         *
         *     On success: returns the normalized Scenario dict (HTTP 200).
         *     On failure: returns HTTP 422 with field-keyed error list.
         *     Never leaks a Python traceback (RG-9.4).
         *
         *     Satisfies AC-RG-2.4, RG-2.3, AC-RG-3.9.
         */
        post: operations["validate_scenario_api_scenario_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Simulate
         * @description Run a deterministic 6-DOF simulation and return serialized results.
         *
         *     Satisfies REQ-01.3, REQ-02.2, REQ-02.3, REQ-03.2, REQ-07.1, REQ-07.3,
         *     RG-2.4, AC-RG-2.5, AC-RG-2.6, RG-9.2, ADR-6.
         */
        post: operations["run_simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Atmosphere
         * @description Atmosphere model selection and fallback policy.
         *
         *     Parameters
         *     ----------
         *     model : str
         *         One of ``forecast``, ``wyoming_sounding``, ``standard_atmosphere``,
         *         ``reanalysis``. Validated at load time (REQ-SCN-03).
         *     file : str or None
         *         For ``forecast``: GFS ensemble name (default ``"GFS"``).
         *         For ``reanalysis``: path to a local ERA5-compatible .nc file (required
         *         when model is ``reanalysis``, REQ-SCN-04).
         *     station : str or None
         *         Wyoming sounding station id. Required when model is
         *         ``wyoming_sounding`` (REQ-SCN-05).
         *     fallback : str
         *         Atmosphere model to use when the primary fetch fails.  Defaults to
         *         ``"standard_atmosphere"`` (REQ-SCN-06).
         */
        Atmosphere: {
            /**
             * Fallback
             * @default standard_atmosphere
             */
            fallback: string;
            /** File */
            file?: string | null;
            /**
             * Model
             * @default standard_atmosphere
             */
            model: string;
            /** Station */
            station?: string | null;
        };
        /**
         * AtmosphereSuggestion
         * @description Response body for GET /api/atmosphere/suggest.
         */
        AtmosphereSuggestion: {
            /**
             * Model
             * @enum {string}
             */
            model: "forecast" | "standard_atmosphere";
            /** Needs Internet */
            needs_internet: boolean;
            /** Reason */
            reason: string;
            /** Within Gfs Window */
            within_gfs_window: boolean;
        };
        /** Body_post_convert_api_convert_post */
        Body_post_convert_api_convert_post: {
            /**
             * File
             * @description OpenRocket .ork file
             */
            file: string;
        };
        /**
         * ConvertResult
         * @description Response body for POST /api/convert.
         */
        ConvertResult: {
            /** Export Id */
            export_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
        };
        /**
         * Dispersion
         * @description Uncertainty dispersion for a single parameter.
         *
         *     Parameters
         *     ----------
         *     std : float
         *         Standard deviation of the dispersion.
         *     kind : {"relative", "absolute"}
         *         ``relative`` — std is a fraction of the nominal value (e.g. 0.05 = 5%).
         *         ``absolute`` — std is in the same units as the nominal (e.g. 2.0°).
         *         ``kind`` is REQUIRED; absent ``kind`` is a validation error (REQ-SCN-08).
         */
        Dispersion: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "relative" | "absolute";
            /** Std */
            std: number;
        };
        /**
         * ElevationLookupResult
         * @description Response body for GET /api/elevation.
         */
        ElevationLookupResult: {
            /** Elevation */
            elevation: number;
            /**
             * Source
             * @constant
             */
            source: "dem";
        };
        /**
         * FlightSeries
         * @description Response body for GET /api/results/{run_id}/series.
         */
        FlightSeries: {
            /** Acceleration */
            acceleration?: number[] | null;
            /** Altitude */
            altitude?: number[] | null;
            /** Mach */
            mach?: number[] | null;
            /** Path3D */
            path3d?: number[][] | null;
            /** Speed */
            speed?: number[] | null;
            /** T */
            t: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityResponse
         * @description Response body for GET /api/auth/me.
         */
        IdentityResponse: {
            /** Email */
            email?: string | null;
            /** Org Id */
            org_id: string;
            /** User Id */
            user_id: string;
        };
        /**
         * LaunchDate
         * @description UTC launch date and hour.
         *
         *     Required for real-atmosphere models (forecast, wyoming_sounding).
         *
         *     Parameters
         *     ----------
         *     year, month, day, hour : int
         *         UTC date and hour of the simulated launch.
         */
        LaunchDate: {
            /** Day */
            day: number;
            /** Hour */
            hour: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /**
         * Rail
         * @description Optional launch rail parameter overrides.
         *
         *     All fields are individually optional (REQ-SCN-09). Present values override
         *     the corresponding fields in the export's ``flight`` block; absent values
         *     keep the export value.
         */
        Rail: {
            /** Heading */
            heading?: number | null;
            /** Inclination */
            inclination?: number | null;
            /** Length */
            length?: number | null;
        };
        /**
         * ResultEnvelope
         * @description Response body for GET /api/results/{run_id}.
         */
        ResultEnvelope: {
            result: components["schemas"]["SimulateResult"];
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @constant
             */
            status: "done";
        };
        /**
         * RocketDetail
         * @description Response body for GET /api/rockets/{rocket_id} — a RocketSummary plus its manifest.
         */
        RocketDetail: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Export Prefix */
            export_prefix: string;
            /** Gcs Ref */
            gcs_ref: string;
            /** Has Source Ork */
            has_source_ork: boolean;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Ork Filename */
            ork_filename: string | null;
            /** Rocket Id */
            rocket_id: string;
        };
        /**
         * RocketSummary
         * @description One rocket as returned by GET /api/rockets.
         */
        RocketSummary: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Export Prefix */
            export_prefix: string;
            /** Gcs Ref */
            gcs_ref: string;
            /** Has Source Ork */
            has_source_ork: boolean;
            /** Name */
            name: string;
            /** Ork Filename */
            ork_filename: string | null;
            /** Rocket Id */
            rocket_id: string;
        };
        /**
         * Scenario
         * @description Root scenario model.  Returned by :func:`load_scenario`.
         *
         *     Parameters
         *     ----------
         *     name : str
         *         Human-readable label for this scenario (used as default MC output prefix).
         *     site : Site
         *         Launch site coordinates.  Required.
         *     date : LaunchDate or None
         *         UTC launch date.  Required when atmosphere.model requires it.
         *     atmosphere : Atmosphere
         *         Atmosphere model configuration.
         *     rail : Rail or None
         *         Optional launch rail parameter overrides.
         *     uncertainty : dict[str, Dispersion] or None
         *         Per-parameter dispersion budget.  ``None`` signals "not set in YAML"
         *         so :func:`load_scenario` can fill DEFAULT_UNCERTAINTY.
         */
        Scenario: {
            /**
             * @default {
             *       "fallback": "standard_atmosphere",
             *       "model": "standard_atmosphere"
             *     }
             */
            atmosphere: components["schemas"]["Atmosphere"];
            date?: components["schemas"]["LaunchDate"] | null;
            /**
             * Name
             * @default unnamed_scenario
             */
            name: string;
            rail?: components["schemas"]["Rail"] | null;
            site: components["schemas"]["Site"];
            /** Uncertainty */
            uncertainty?: {
                [key: string]: components["schemas"]["Dispersion"];
            } | null;
        };
        /**
         * ScenarioTemplate
         * @description Response body for GET /api/scenario/template — a starter Scenario plus uncertainty presets.
         */
        ScenarioTemplate: {
            /**
             * @default {
             *       "fallback": "standard_atmosphere",
             *       "model": "standard_atmosphere"
             *     }
             */
            atmosphere: components["schemas"]["Atmosphere"];
            date?: components["schemas"]["LaunchDate"] | null;
            /**
             * Name
             * @default unnamed_scenario
             */
            name: string;
            rail?: components["schemas"]["Rail"] | null;
            site: components["schemas"]["Site"];
            /** Uncertainty */
            uncertainty?: {
                [key: string]: components["schemas"]["Dispersion"];
            } | null;
            /** Uncertainty Presets */
            uncertainty_presets: {
                [key: string]: {
                    [key: string]: components["schemas"]["Dispersion"];
                };
            };
        };
        /**
         * SessionRequest
         * @description Request body for POST /api/auth/session.
         */
        SessionRequest: {
            /** Id Token */
            id_token: string;
        };
        /**
         * SimulateRequest
         * @description Request body for POST /api/simulate.
         */
        SimulateRequest: {
            /** Export Id */
            export_id: string;
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
        };
        /**
         * SimulateResult
         * @description Response body for POST /api/simulate.
         */
        SimulateResult: {
            /** Plot Urls */
            plot_urls: string[];
            /** Run Id */
            run_id: string;
            /** Scalars */
            scalars: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
        };
        /**
         * SimulationSummary
         * @description One simulation as returned by GET /api/history.
         */
        SimulationSummary: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Has Series */
            has_series: boolean;
            /** Name */
            name: string;
            /** Plot Names */
            plot_names: string[];
            /** Result Prefix */
            result_prefix: string;
            /** Rocket Id */
            rocket_id: string;
            /** Scalars */
            scalars: {
                [key: string]: unknown;
            };
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Simulation Id */
            simulation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "error";
            /** Warnings */
            warnings: string[];
        };
        /**
         * Site
         * @description Launch site coordinates.
         *
         *     Parameters
         *     ----------
         *     latitude : float
         *         WGS-84 latitude in decimal degrees. Required. Range: -90 to 90.
         *     longitude : float
         *         WGS-84 longitude in decimal degrees. Required. Range: -180 to 180.
         *     elevation : float or None
         *         Altitude above sea-level in metres. When absent the elevation from the
         *         export's ``environment`` block is used (REQ-SCN-10).
         */
        Site: {
            /** Elevation */
            elevation?: number | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    suggest_atmosphere_api_atmosphere_suggest_get: {
        parameters: {
            query: {
                /** @description ISO 8601 date+time for the launch */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtmosphereSuggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
        };
    };
    create_session_api_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_convert_api_convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_convert_api_convert_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_elevation_api_elevation_get: {
        parameters: {
            query: {
                /** @description WGS-84 latitude in decimal degrees */
                lat: number;
                /** @description WGS-84 longitude in decimal degrees */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElevationLookupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_results__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plot_api_results__run_id__plots__name__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_results__run_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rockets_api_rockets_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RocketSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rocket_api_rockets__rocket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rocket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RocketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_template_api_scenario_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioTemplate"];
                };
            };
        };
    };
    validate_scenario_api_scenario_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
